name: Deploy Landing to Server

on:
  push:
    branches: [main, master]

jobs:
  deploy:
    runs-on: [self-hosted, ubuntu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t landing-site:latest .

      - name: Deploy Container
        run: |
          # Останавливаем старый контейнер, если он есть
          docker stop landing-site  true
          docker rm landing-site  true

          # Запускаем новый с лейблами для Traefik
          docker run -d \
            --name landing-site \
            --restart unless-stopped \
            --network proxy \
            --label "traefik.enable=true" \
            --label "traefik.http.routers.landing.rule=Host(\`skeletonfx.ru\`)" \
            --label "traefik.http.routers.landing.entrypoints=web" \
            --label "traefik.http.routers.landing-secure.rule=Host(\`skeletonfx.ru\`)" \
            --label "traefik.http.routers.landing-secure.entrypoints=websecure" \
            --label "traefik.http.routers.landing-secure.tls=true" \
            --label "traefik.http.routers.landing-secure.tls.certresolver=cloudflare" \
            --label "traefik.http.services.landing.loadbalancer.server.port=80" \
            landing-site:latest
